services:
  file_drive_db:
    image: postgres:15.8-bullseye
    container_name: file-drive-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - file-drive-data:/var/lib/postgresql/data
    ports:
      - "5030:5432"

volumes:
  file-drive-data: