name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.8-bullseye
        ports:
          - 5030:5432
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: y7jHf&DNWG15
          POSTGRES_DB: main
        options: >
          --health-cmd="pg_isready -U admin" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run tests
        run: poetry run pytest --disable-warnings --cov=.
        env:
          PYTHONPATH: .
          DATABASE_URL: postgresql+asyncpg://admin:y7jHf&DNWG15@localhost:5030/main
          JWT_SECRET_KEY: pD/jHobTwG7Tw2YtV9RLs577JEUCWcgJEDVm7RejznQ=
          JWT_ALGORITHM: HS256
          GCS_BUCKET_NAME: file-drive-uploads-vegax-429008-test
          GOOGLE_CLOUD_PROJECT: file-drive-vegax-429008
          GOOGLE_CLOUD_REGION: asia-northeast3

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/file-drive-repo/filedrive:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/file-drive-repo/filedrive:latest
