name: Build and push Docker image to Docker Hub

on:
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t mjthecoder10/file-drive:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: mjthecoder10
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker image
        run: docker push mjthecoder10/file-drive:latest
